var audio = new Audio('sound/mainMenu.mp3');
var soundButton = new Image();
var player = new Image();
player.src = 'textures/player/playerModel.png';
var coin = new Image();
coin.src = 'textures/coin.png';
var spikes = new Image;
spikes.src = 'textures/spikes.png';
var levelButtonRed = new Image();
levelButtonRed.src = 'textures/levelButtonRed.png';
var levelButtonGreen= new Image();
levelButtonGreen.src = 'textures/levelButtonGreen.png';
var key = new Image();
key.src = 'textures/key.png';
var teleportCoin = new Image();
teleportCoin.src = 'textures/teleportCoin.png';
var apple = new Image();
apple.src = 'textures/apple.png';
var jump = new Audio('sound/jump.mp3'); //https://freesound.org/people/kwahmah_02/sounds/262893/
var coinGrab = new Audio('sound/coinGrab.mp3'); //https://freesound.org/people/plasterbrain/sounds/242857/
var touchSpike = new Audio('sound/touchSpike.mp3'); //https://freesound.org/people/Deathscyp/sounds/443806/
var error = new Audio('sound/error.mp3'); //https://freesound.org/people/Breviceps/sounds/450616/
var buttonSound = new Audio('sound/button.mp3'); //https://freesound.org/people/Deathscyp/sounds/404049/
var grabKey = new Audio('sound/keyGrab.mp3'); //https://freesound.org/people/sophiehall3535/sounds/248037/
var teleportSound = new Audio('sound/teleport.mp3'); //https://freesound.org/people/Sergenious/sounds/55853/
var mainMenuButton = new Image();
mainMenuButton.src = 'textures/buttons/mainMenu.png';
var youWon = new Audio('sound/youWon.mp3'); //https://freesound.org/people/FunWithSound/sounds/369252/
var gameOver = new Audio('sound/gameOver.mp3'); //https://freesound.org/people/yummie/sounds/410575/
var appleBite = new Audio('sound/appleBite.mp3'); //https://freesound.org/people/wadaltmon/sounds/275015/