function level2(){
    return [
        new Background(2),
        new Block(15, 8, "block"),
        new Block(14, 27, "block"),
        new Block(14, 28, "block"),
        new Block(13, 5, "block"),
        new Block(13, 6, "block"),
        new Block(13, 7, "block"),
        new Block(13, 8, "block"),
        new Block(13, 20, "block"),
        new Block(13, 21, "block"),
        new Block(13, 22, "block"),
        new Block(13, 23, "block"),
        new Block(10, 1, "block"),
        new Block(10, 2, "block"),
        new Block(10, 12, "block"),
        new Block(10, 13, "block"),
        new Block(10, 14, "block"),
        new Block(10, 15, "block"),
        new Block(10, 16, "block"),
        new Block(8, 5, "block"),
        new Block(8, 6, "block"),
        new Block(8, 7, "block"),
        new Block(8, 8, "block"),
        new Block(8, 20, "block"),
        new Block(8, 21, "block"),
        new Block(8, 22, "block"),
        new Block(8, 23, "block"),
        new Block(7, 14, "block"),
        new Block(7, 28, "block"),
        new Block(6, 1, "block"),
        new Block(4, 4, "block"),
        new Block(4, 5, "block"),
        new Block(4, 6, "block"),
        new Block(4, 7, "block"),
        new Block(4, 8, "block"),
        new Block(4, 9, "block"),
        new Block(4, 10, "block"),
        new Block(4, 11, "block"),
        new Block(4, 12, "block"),
        new Block(4, 16, "block"),
        new Block(4, 17, "block"),
        new Block(4, 18, "block"),
        new Block(4, 19, "block"),
        new Block(4, 20, "block"),
        new Block(4, 21, "block"),
        new Block(4, 22, "block"),
        new Block(4, 23, "block"),
        new Block(4, 24, "block"),
        new Block(4, 25, "block"),
        new Block(4, 26, "block"),

        new Spike(14, 12, "spike"),
        new Spike(14, 13, "spike"),
        new Spike(14, 14, "spike"),
        new Spike(12, 26, "spike"),
        new Spike(8, 0, "spike"),
        new Spike(5, 13, "spike"),
        new Spike(2, 6, "spike"),
        new Spike(2, 7, "spike"),
        new Spike(2, 19, "spike"),
        new Spike(2, 20, "spike"),
        
        new Coin(13, 5, "coin"),
        new Coin(13.5, 9.5, "coin"),
        new Coin(12, 27.25, "coin"),
        new Coin(11.5, 13.25, "coin"),
        new Coin(7.5, 13.25, "coin"),
        new Coin(4, 27.25, "coin"), 
        new Coin(2, 18.25, "coin"),
        new Coin(2, 3, "coin"),
        new Coin(1.75, 23, "coin"),
        new Coin(1, 5, "coin"),

        new TeleportCoin(10.5, 20.5, "teleportCoin"),
        new TeleportCoin(6.2, 5.75, "teleportCoin"),

        new Bonus(2, 9, "bonus"),
        new Bonus(11, 5.5, "bonus"),

        new Button(1.5, 25.25, "button", false),

        new Key(14.3, 27, "key", false)
    ];
}